# Subset data curation with MeSO optimizer (exact scoring)
method: Subset
finetuning: MeSO
learning_rate: 3.00e-05
subset_mode: two_pass
scoring:
  method: reduced_ghost

optimizer:
  compression: normal-512*512
