# Layerwise data curation with MeSO optimizer
method: Layerwise
scoring_method: compress
finetuning: MeSO
learning_rate: 4.83e-06

score_grad_compression:
  sparsifier: normal-512*512
  projector: none

opt_grad_compression:
  sparsifier: normal-512*512
  projector: none
