# Layerwise data curation with MeSO optimizer
method: Layerwise
finetuning: MeSO
learning_rate: 4.83e-06

scoring:
  method: compress
  compression: normal-512*512
optimizer:
  compression: normal-512*512
