# Subset data curation with MeSO optimizer (exact scoring)
method: Subset
subset_mode: one_pass
scoring:
  method: reduced_ghost
finetuning: MeSO
learning_rate: 4.83e-06

optimizer:
  compression: normal-512*512
