# Subset data curation with MeSO optimizer (exact scoring)
method: Subset
subset_mode: two_pass
scoring:
  method: reduced_ghost
finetuning: MeSO
learning_rate: 9.00e-07

optimizer:
  compression: normal-512*512
