# Subset data curation with LoRA fine-tuning (exact scoring)
method: Subset
finetuning: LoRA
learning_rate: 1.07e-05
lora_r: 32
lora_alpha: 1
lora_dropout: 0.1

score_grad_compression:
  sparsifier: none
  projector: none
